### ISSUE TITLE
How to run ParseServer?

### ISSUE THREAD

**Issue by YamahaYori** [zebapy/react-redux-parse-server#35]
I have installed this app on my local side.
And signup and login are working or not?
Please guide me how to install them and run parse server to make it work.

**Comment by zebapy** [comment]
Did you follow https://github.com/zebapy/react-redux-parse-server#getting-started?

**Comment by YamahaYori** [comment]
Yes, localhost:3000, I can see signup form and login form.
But I want to make them work. When I press login or signup, it doesn't work.

**Comment by YamahaYori** [comment]
I have no idea how to handle parse server.

**Comment by zebapy** [comment]
Do you have 2 terminals running and mongodb locally running?

**Comment by YamahaYori** [comment]
brew services start mongodb
I did it for mongodb running.

**Comment by YamahaYori** [comment]
One is app running and One is for MongoDb running.
Should I do something with DatabaseURI?
Please guide me make it work on my localside.
Thanks

**Comment by zebapy** [comment]
I will have to follow up over the weekend, sorry. You could try the simpler version of this here https://github.com/zebapy/create-react-app-parse-redux which uses create-react-app. 

You shouldn't have to change the databaseURI if mongodb is running on local, ref: https://github.com/zebapy/react-redux-parse-server/blob/master/src/server.js#L20

**Comment by YamahaYori** [comment]
Do you mean if I install this app and run mongodb, it would work without any issue?

**Comment by zebapy** [comment]
Theoretically both should but as you can see from commit history I haven't updated them in awhile. I use Apollo+Graphql now. I will try to make sure this works as is over the weekend. Last I knew, it worked fine.

**Comment by YamahaYori** [comment]
How can I see the content of dev database?
And How can I check DB is working properly?
I just did 'npm start' and nothing has been changed on the source.

**Comment by zebapy** [comment]
You may want to familiarize yourself with interacting with mongodb shell usage to inspect db content https://docs.mongodb.com/manual/mongo/#introduction

The other repo has parse-dashboard for also viewing db content. If we are discussing this repo, let's keep the discussion here. Otherwise new issues should be on the other one.

**Comment by YamahaYori** [comment]
I have tried with creat-react-app also. Same issue.
Maybe I have some problems for my environment.
Why is it so difficult to run on my side?
The instruction seems easy and I just did 'npm install'and 'num start'.
What more shall I do now?

**Comment by zebapy** [comment]
Tomorrow I will look these over and get back to you.

**Comment by YamahaYori** [comment]
That would be great...I am sorry to disturb your weekend.
Thanks again for your prompt response and kind support.

**Comment by YamahaYori** [comment]
Hi, there....Can we continue?

**Comment by zebapy** [comment]
So i just tested both repos and no issues on my end. 

I cloned this repo, did `npm install` then did the following:

- Open 3 terminal windows
- in one, since I have mongodb installed (separate step from installing the node modules), I run `mongod` and it shows `MongoDB starting : pid=12537 port=27017...` and some more info.
- In the second, I do `npm run start-dev`
- In the third, `npm run watch-client`

I was able to complete and submit the sign up form. Also assuming youre on a mac as I havent tested this or intended to build the repo for PC.

**Comment by YamahaYori** [comment]
What about dbpath for mongodb start?

**Comment by zebapy** [comment]
yes that shows up

**Comment by YamahaYori** [comment]
Ok Let me reinstall Mongodb and restart

**Comment by YamahaYori** [comment]
I am sorry but can u guide me how to solve this?
/data/db not found error

**Comment by zebapy** [comment]
Maybe try signing up for free https://mlab.com/ and replace the database uri with the one you get on mlab https://github.com/zebapy/react-redux-parse-server/blob/master/src/server.js#L20 

I don't really have much time to troubleshoot issues outside of ones for this repo, sorry. 

Also stack overflow has some results for that issue http://stackoverflow.com/questions/7948789/mongodb-mongod-complains-that-there-is-no-data-db-folder

**Comment by YamahaYori** [comment]
OK...It worked...Thanks
